version: '3.1'
services:
  db:
    image: postgres:12-alpine
    ports:
      - '8080:8080'
    volumes:
      - ./data:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: 1111
      POSTGRES_USER: app
      POSTGRES_DB: db